
#include "stdafx.h"
#include "plugin.h"

#ifdef _DEBUG
#undef THIS_FILE
static char THIS_FILE[]=__FILE__;
#define new DEBUG_NEW
#endif

//#pragma warning (disable:4838)

ULONG Civ_All_Status[] = 
{
	CIV_READ_ID,
	CIV_MAIN_POWER,
	CIV_DV_MY_CALLSIGN1,
	CIV_DV_MY_CALLSIGN2,
	CIV_DV_MY_CALLSIGN3,
	CIV_DV_MY_CALLSIGN4,
	CIV_DV_MY_CALLSIGN5,
	CIV_DV_MY_CALLSIGN6,
	CIV_DV_MY_CALLSIGN_MEMCH,
	CIV_DV_TX_CALLSIGN,
	CIV_DV_TX_MESSAGE1,
	CIV_DV_TX_MESSAGE2,
	CIV_DV_TX_MESSAGE3,
	CIV_DV_TX_MESSAGE4,
	CIV_DV_TX_MESSAGE5,
	CIV_DV_TX_MESSAGE_MEMCH,
	CIV_DV_TX_MESSAGE_ENABLE,
	CIV_READ_FREQUENCY1,
	CIV_READ_FREQUENCY2,
	CIV_DUPLEX_MODE1,
	CIV_DUPLEX_MODE2,
	CIV_READ_DUPLEX_OFFSET1,
	CIV_READ_DUPLEX_OFFSET2,
	CIV_AF_VOLUME1,
	CIV_AF_VOLUME2,
	CIV_SQL_LEVEL1,
	CIV_SQL_LEVEL2,
	CIV_MAIN_BAND_SELECTION,
	CIV_DUAL_WATCH_MODE,
	CIV_READ_OPERATING_MODE1,
	CIV_READ_OPERATING_MODE2,
	CIV_NOISE_SQL1,
	CIV_NOISE_SQL2,
	CIV_SIGNAL_LEVEL1,
	CIV_SIGNAL_LEVEL2,
	CIV_VFO_MR_CALL_SELECTION1,
	CIV_VFO_MR_CALL_SELECTION2,
	CIV_RF_POWER1,
	CIV_RF_POWER2,
	CIV_ATTENUATOR,
	CIV_MONITOR_MODE,
	CIV_PTT_STATUS,
	CIV_DV_EMERGENCY_MODE,
	CIV_DV_BREAK_IN_MODE

};

ULONG *g_Civ_All_Status = Civ_All_Status;
ULONG g_nCiv_All_Status = _countof (Civ_All_Status);

