//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// IDControl.rc で使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_IDControlTYPE               130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_REPEATERVIEW            133
#define ID_VIEW_DEBUGVIEW               134
#define ID_SET_TO_CALLSIGN              137
#define ID_SET_FROM_CALLSIGN            138
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_POPUP_REPEATER              174
#define IDB_TREE_VIEW                   175
#define IDB_TREE_VIEW_24                176
#define ID_TOOLS_MACRO                  181
#define IDB_DIGIT_PTT_ON_NG_PNG         200
#define IDB_DIGIT_PTT_ON_OK_PNG         201
#define IDB_DIGIT_PW_OFF_PNG            202
#define IDB_DIGIT_ENABLE_PNG            203
#define IDB_DIGIT_DISABLE_PNG           204
#define IDB_SMETER_ENABLE_PNG           205
#define IDB_SMETER_DISABLE_PNG          206
#define IDB_SMETER_PW_OFF_PNG           207
#define ID_VIEW_CALLSIGN_HISTORYVIEW    285
#define ID_VIEW_MESSAGE_HISTORYVIEW     286
#define ID_VIEW_COMMONVIEW              287
#define ID_VIEW_ANALOG_FREQ_VIEW        288
#define ID_VIEW_DIGITAL_FREQ_VIEW       289
#define ID_VIEW_GPS_HISTORYVIEW         290
#define IDD_TRX_SETTING                 310
#define IDC_PLUGIN_COMBO                400
#define IDC_PLUGIN_LABEL                401
#define IDC_COMPORT_COMBO               402
#define IDC_COMPORT_LABEL               403
#define IDC_SPEAKER_PLUGIN_COMBO        403
#define IDC_HOST_ADDR_LABEL             404
#define IDC_HOST_ADDR_EDIT              405
#define IDC_HOST_PORT_LABEL             406
#define IDC_HOST_PORT_EDIT              407
#define IDC_SERVER_PORT_EDIT            408
#define IDC_SERVER_PORT_CHECK           409
#define IDC_RIGHT_AND_LEFT_CURSOR       500
#define IDC_TOP_AND_BOTTOM_CURSOR       501
#define IDR_WAVE_SPACE                  546
#define IDR_WAVE_SLASH                  547
#define IDR_WAVE_0                      548
#define IDR_WAVE_1                      549
#define IDR_WAVE_2                      550
#define IDR_WAVE_3                      551
#define IDR_WAVE_4                      552
#define IDR_WAVE_5                      553
#define IDR_WAVE_6                      554
#define IDR_WAVE_7                      555
#define IDR_WAVE_8                      556
#define IDR_WAVE_9                      557
#define IDR_WAVE_A                      565
#define IDR_WAVE_B                      566
#define IDR_WAVE_C                      567
#define IDR_WAVE_D                      568
#define IDR_WAVE_E                      569
#define IDR_WAVE_F                      570
#define IDR_WAVE_G                      571
#define IDR_WAVE_H                      572
#define IDR_WAVE_I                      573
#define IDR_WAVE_J                      574
#define IDR_WAVE_K                      575
#define IDR_WAVE_L                      576
#define IDR_WAVE_M                      577
#define IDR_WAVE_N                      578
#define IDR_WAVE_O                      579
#define IDR_WAVE_P                      580
#define IDR_WAVE_Q                      581
#define IDR_WAVE_R                      582
#define IDR_WAVE_S                      583
#define IDR_WAVE_T                      584
#define IDR_WAVE_U                      585
#define IDR_WAVE_V                      586
#define IDR_WAVE_W                      587
#define IDR_WAVE_X                      588
#define IDR_WAVE_Y                      589
#define IDR_WAVE_Z                      590
#define IDD_DIALOG1                     600
#define IDD_EDIT                        600
#define IDD_EDIT_MY_CALLSIGN            601
#define IDD_SOUND_SETTING               602
#define IDC_EDIT1                       1010
#define IDC_EDIT2                       1011
#define IDC_MEMO_EDIT                   1011
#define IDC_CALLSIGN_EDIT               1012
#define IDC_MIC_PLUGIN_COMBO            1014
#define IDC_MIC_PLUGIN_CHECK            1015
#define IDC_SPEAKER_PLUGIN_CHECK        1016
#define IDS_OK_BUTTON                   1801
#define IDS_CANCEL_BUTTON               1802
#define IDS_STATUS_PANE1                1822
#define IDS_STATUS_PANE2                1823
#define IDS_TOOLBAR_CUSTOMIZE           1825
#define IDS_FILE_VIEW                   1855
#define IDS_REPEATER_VIEW               1855
#define IDS_DEBUG_VIEW                  1856
#define IDS_HISTORY_VIEW                1859
#define IDS_CALLSIGN_HISTORY_VIEW       1859
#define IDS_MESSAGE_HISTORY_VIEW        1860
#define IDS_COMMON_VIEW                 1861
#define IDS_ANALOG_FREQ_VIEW            1862
#define IDS_DIGITAL_FREQ_VIEW           1863
#define IDS_GPS_HISTORY_VIEW            1864
#define IDS_REPEATER                    1905
#define IDS_TRX_SETTING_TITLE           2001
#define IDS_TRX_SETTING_PLUGIN_LABEL    2002
#define IDS_TRX_SETTING_COM_LABEL       2003
#define IDS_TRX_SETTING_SERVER_PORT_CHECK 2004
#define IDS_TRX_SETTING_REMOTE_ADDR_LABEL 2005
#define IDS_TRX_SETTING_REMOTE_PORT_LABEL 2006
#define IDS_TRX_SETTING_USER_NAME_LABEL 2007
#define IDS_TRX_SETTING_USER_PASS_LABEL 2008
#define IDS_HISTORY_VIEW_DATETIME       2020
#define IDS_HISTORY_VIEW_CALLER         2021
#define IDS_HISTORY_VIEW_MEMO           2022
#define IDS_HISTORY_VIEW_CALLED         2023
#define IDS_HISTORY_VIEW_RX_RPT1        2024
#define IDS_HISTORY_VIEW_RX_RPT2        2025
#define IDS_HISTORY_VIEW_STATUS         2026
#define IDS_HISTORY_VIEW_MESSAGE        2027
#define IDS_HISTORY_VIEW_GPS            2028
#define IDC_USER_NAME_LABEL             2030
#define IDC_USER_NAME_EDIT              2031
#define IDC_USER_PASS_LABEL             2032
#define IDC_USER_PASS_EDIT              2033
#define IDS_SOUND_SETTING_TITLE         2050
#define IDS_SOUND_SETTING_MIC_CHECK     2051
#define IDS_SOUND_SETTING_SPEAKER_CHECK 2052
#define ID_CMD_TRX_SETTING              32772
#define ID_CMD_IMPORT_REPEATER_LIST     32774
#define ID_32775                        32775
#define ID_CMD_SOUND_SETTING            32776
#define ID_FILE_PRINT                   0xE107
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        602
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
